[package]
name = "webgame-collection-api-macros"
version = "0.1.0"
authors = ["XiNiHa <anesin1109@naver.com>"]
edition = "2018"
resolver = "2"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.29"
syn = "1.0.75"
quote = "1.0"
